name: Build
on: [push, pull_request]

env:
  DOTNET_NOLOGO: 1
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x

      - name: Build
        working-directory: ./src
        run: dotnet build --configuration Release

      - name: Upload package
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Package
          path: "**/*.nupkg"
